KSWA-SWEEP/jaksim31-backend

- .gitignore
- src/main/java/com/sweep/jaksim31/controller/DiaryApiController.java
- src/main/java/com/sweep/jaksim31/dto/diary/DiaryDTO.java
- src/main/java/com/sweep/jaksim31/entity/diary/Diary.java
- src/main/java/com/sweep/jaksim31/entity/diary/DiaryRepository.java
- src/main/java/com/sweep/jaksim31/service/DiaryService.java
- src/main/java/com/sweep/jaksim31/service/impl/DiaryServiceImpl.java
Init Diary API
- read all diaries
- save dairy
- update diary
- delete diary
- find diary by diary_id
- search diary
> SW-66 Feature/diary crud

- pom.xml
- src/main/java/com/sweep/jaksim31/controller/DiaryApiController.java
- src/main/java/com/sweep/jaksim31/dto/diary/DiaryDTO.java
- src/main/java/com/sweep/jaksim31/entity/diary/Diary.java
- src/main/java/com/sweep/jaksim31/entity/diary/DiaryRepository.java
- src/main/java/com/sweep/jaksim31/service/impl/DiaryServiceImpl.java
- src/main/java/com/sweep/jaksim31/util/exceptionhandler/DiaryExceptionType.java
Update Diary API
- Add Error Handling and Validation
- Add Tag of APIs
> SW-66 feat(diary):Apply feedback and Add Error handling

- src/main/java/com/sweep/jaksim31/controller/DiaryApiController.java
- src/main/java/com/sweep/jaksim31/dto/diary/DiaryInfoDTO.java
- src/main/java/com/sweep/jaksim31/dto/member/MemberInfoDTO.java
- src/main/java/com/sweep/jaksim31/dto/member/MemberRespDTO.java
- src/main/java/com/sweep/jaksim31/entity/diary/Diary.java
- src/main/java/com/sweep/jaksim31/service/DiaryService.java
- src/main/java/com/sweep/jaksim31/service/impl/DiaryServiceImpl.java
- src/main/java/com/sweep/jaksim31/util/exceptionhandler/DiaryExceptionType.java
- "id" in MemberRespDTO -> "userId"
- "id" in DiaryInfoDTO -> "diaryId"
> SW-77 feat(DTO):edit MemberRespDTO and add DiaryInfoDTO

- src/main/java/com/sweep/jaksim31/controller/DiaryApiController.java
- src/main/java/com/sweep/jaksim31/domain/diary/DiaryRepository.java
- src/main/java/com/sweep/jaksim31/dto/diary/DiaryThumbnailRequest.java
- src/main/java/com/sweep/jaksim31/service/DiaryService.java
- src/main/java/com/sweep/jaksim31/service/impl/DiaryServiceImpl.java
- src/main/java/com/sweep/jaksim31/service/impl/MemberServiceImpl.java
- 사용자 로그인 시 사용자 정보를 받아오는 api에서 사용자 정보와 함께 오늘 일기 정보(todayDiaryId)를 Header의 cookie값으로 설정하여 보내주도록 수정.  
- 오늘 일기 정보가 있으면 diaryId, 없으면 ""
- 만료 시간은 당일 23:59:59
> SW-88 feat(diary) : Feature/diary today

- LICENSE
- pom.xml
- src/main/java/com/sweep/jaksim31/auth/JwtFilter.java
- src/main/java/com/sweep/jaksim31/controller/MembersApiController.java
- src/main/java/com/sweep/jaksim31/domain/members/Members.java
- src/main/java/com/sweep/jaksim31/dto/login/KakaoProfile.java
- src/main/java/com/sweep/jaksim31/dto/member/MemberCheckLoginIdRequest.java
- src/main/java/com/sweep/jaksim31/dto/member/MemberCheckPasswordRequest.java
- src/main/java/com/sweep/jaksim31/dto/member/MemberInfoResponse.java
- src/main/java/com/sweep/jaksim31/dto/member/MemberRemoveRequest.java
- src/main/java/com/sweep/jaksim31/dto/member/MemberSaveResponse.java
- src/main/java/com/sweep/jaksim31/dto/member/MemberUpdateRequest.java
- src/main/java/com/sweep/jaksim31/dto/token/TokenRequest.java
- src/main/java/com/sweep/jaksim31/exception/BizException.java
- src/main/java/com/sweep/jaksim31/exception/handler/ApiExceptionHandler.java
- src/main/java/com/sweep/jaksim31/exception/handler/RedirectionResponse.java
- src/main/java/com/sweep/jaksim31/exception/type/JwtExceptionType.java
- src/main/java/com/sweep/jaksim31/exception/type/MemberExceptionType.java
- src/main/java/com/sweep/jaksim31/service/impl/KaKaoMemberServiceImpl.java
- src/main/java/com/sweep/jaksim31/service/impl/MemberServiceImpl.java
- src/main/java/com/sweep/jaksim31/utils/JsonUtil.java
- src/main/java/com/sweep/jaksim31/utils/RedirectionUtil.java
- src/test/java/com/sweep/jaksim31/MiscTest.java
- src/test/java/com/sweep/jaksim31/config/TestConfig.java
- src/test/java/com/sweep/jaksim31/controller/MembersApiControllerTest.java
- src/test/java/com/sweep/jaksim31/controller/MembersApiControllerTest123.java
[추가]
1. JsonUtil.java 추가(Object -> Json String)
2. Member 컨트롤러 유닛 테스트 코드 추가
[수정]
1. ExceptionHandler에 Redirection 시 location 조건 추가
2. BizException 생성자 오버로딩 (location 필드 추가로 인한)
3. Member controller 클래스 타입 ? -> String
> SW-98 add member controller unit test

- .gitignore
- src/main/java/com/sweep/jaksim31/domain/diary/DiaryRepository.java
- src/main/java/com/sweep/jaksim31/service/impl/DiaryServiceImpl.java
- src/test/java/com/sweep/jaksim31/domain/diary/DiaryRepositoryTest.java
- `DiaryRepositoryTest` 테스트 케이스 추가 및 수정
> 추가) 일기 삭제, 오늘 일기 저장, 일기 전체 조회, 오늘 일기 조회, 사용자 일기 조건 검색
> 수정) 사용자 일기 전체 조회 : 조회 된 diary들의 userId가 검색 조건과 일치하는지 확인
- `.gitignore` 수정
> `src/test/resources/application.yml`  추가
> SW-107 Feature/diary repository test

- src/main/java/com/sweep/jaksim31/controller/DiaryApiController.java
- src/main/java/com/sweep/jaksim31/controller/MembersApiController.java
- src/main/java/com/sweep/jaksim31/dto/diary/DiarySaveRequest.java
- src/main/java/com/sweep/jaksim31/dto/diary/validator/DiaryAnalysisRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/diary/validator/DiarySaveRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/diary/validator/DiaryThumbnailRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/login/validator/LoginRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/member/validator/MemberCheckLoginIdRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/member/validator/MemberCheckPasswordRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/member/validator/MemberRemoveRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/member/validator/MemberSaveRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/member/validator/MemberUpdatePasswordRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/member/validator/MemberUpdateRequestValidator.java
- src/main/java/com/sweep/jaksim31/dto/token/validator/TokenRequestValidator.java
- src/main/java/com/sweep/jaksim31/exception/type/DiaryExceptionType.java
- src/main/java/com/sweep/jaksim31/exception/type/MemberExceptionType.java
- DiarySaveRequest, DiaryThumbnailRequest, DiarySaveRequest의 input value 검증을 위한 Validation 추가
> 각 Request 별 Validator 추가
>  Validation에서 throw할 Exception type 추가(DiaryExceptionType)
> 검증이 필요한 Contoller에 `@Validated` 추가
- Members, Login, Token Request dto의 input value 검증을 위한 Validation 추가
> 각 Request 별 Validator 추가
> Validation에서 throw할 Exception type 추가(MemberExceptionType)
> 검증이 필요한 Contoller에 `@Validated` 추가
> SW-116 Feature/validation

- src/main/java/com/sweep/jaksim31/auth/TokenProvider.java
- src/main/java/com/sweep/jaksim31/controller/MembersApiController.java
- src/main/java/com/sweep/jaksim31/dto/token/TokenResponse.java
- src/main/java/com/sweep/jaksim31/service/impl/KaKaoMemberServiceImpl.java
- src/main/java/com/sweep/jaksim31/service/impl/MemberServiceImpl.java
- src/test/java/com/sweep/jaksim31/controller/MembersApiControllerTest.java
- src/test/java/com/sweep/jaksim31/service/impl/MemberServiceImplTest.java
[수정]
1. 로그인 api 호출 query param 추가 : String redirectUri
2. 로그인 시 userInfo 포함하여 응답하도록 수정
3. 로그인 서비스, 컨트롤러 단위 테스트 코드 수정
> SW-117 modify login api

- src/main/java/com/sweep/jaksim31/controller/DiaryApiController.java
- src/main/java/com/sweep/jaksim31/service/impl/DiaryServiceImpl.java
- 사용자 일기 조회(조건 조회) 서비스 수정
1. 날짜 조회 오류 수정
2. 키워드(searchWord) 검색 조건 추가
> SW-118 feat(diary): Modify findDiaries Service

- Dockerfile
1. ENTRYPOINT에 Sprong profile 옵션 추가
> modify Dockerfile

- src/main/java/com/sweep/jaksim31/config/cache/ProdCacheConfig.java
- src/main/java/com/sweep/jaksim31/config/cache/RedisInfo.java
ProdCacheConfig 수정 - 레디스에 캐싱되지 않는 현상 발견 및 조치
> modify cache config

- .github/workflows/backend.yml
- pom.xml
- scripts/deploy.sh
1. private subnet 생성으로 인한 action 수정
2. 배포 스크립트 수정 (log 저장 volume 옵션 추가)
> modify action & deploy scripts because of creating private subnet

- pom.xml
- src/main/java/com/sweep/jaksim31/auth/JwtFilter.java
- src/main/java/com/sweep/jaksim31/config/SecurityConfig.java
Loadbalancer가 healthcheck 하는 path에 대해 권한 인증 제거
> remove auth check for actuator

- .github/workflows/backend.yml
- pom.xml
- scripts/deploy2.sh
- src/main/java/com/sweep/jaksim31/auth/JwtFilter.java
- src/main/java/com/sweep/jaksim31/config/SecurityConfig.java
1.로깅을 설정을 위해 배포 script 분리
=> github action workflow도 수정
2. health chcek 경로 권한인증 제거
> add deploy shell script for secondary server

- .github/workflows/backend.yml
> modify application.yml

- .github/workflows/backend.yml
CI 과정 수정
* Github action -> Sonarqube Analysis job에  Caching 추가
> add dependency cache for sonarqube job

- pom.xml
- src/main/java/com/sweep/jaksim31/adapter/RestPage.java
- src/main/java/com/sweep/jaksim31/config/AbstractElasticsearchConfiguration.java
- src/main/java/com/sweep/jaksim31/config/ElasticSearchConfig.java
- src/main/java/com/sweep/jaksim31/controller/DiaryApiController.java
- src/main/java/com/sweep/jaksim31/domain/diary/DiarySearch.java
- src/main/java/com/sweep/jaksim31/domain/diary/DiarySearchQueryRepository.java
- src/main/java/com/sweep/jaksim31/dto/diary/DiaryInfoResponse.java
- src/main/java/com/sweep/jaksim31/service/DiaryService.java
- src/main/java/com/sweep/jaksim31/service/impl/DiaryServiceImpl.java
- src/test/java/com/sweep/jaksim31/controller/DiaryApiControllerTest.java
- src/test/java/com/sweep/jaksim31/integration/IntegrationDiaryTest.java
- findDiaries method name 변경 -> searchUserDiaries
- searchUserDiaries 수정
> Mongotemplate 사용하여 search -> ElasticSearch 사용하여 search
> Test코드 추가 : DiaryApiControllerTest
> SW-149 modify findDiaries -> searchUserDiaries

- src/main/java/com/sweep/jaksim31/domain/diary/DiarySearchQueryRepository.java
> SW-149 modify search user diaries service(by ElasticSearch)

- .github/workflows/backend.yml
1. root directory의  의문의 파일 제거
2. deploy 과정 health check step 추가
> remove temp file & add health check step in deploy action

- scripts/deploy.sh
- scripts/deploy2.sh
> SW-149 Modify Deploy.sh  

- scripts/deploy.sh
- scripts/deploy2.sh
1. 배포 스크립트 수정
* 배포 시 기존 컨테이너 삭제 안되는 현상 수정
> SW-149 modify deploy scripts
